name: test

on:
  push:
    branches:
      - master
    paths:
      - "client/**"
      - ".github/workflows/test-client.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 14
      - name: Test client
        working-directory: ./client
        run: npm install && npm run test:ci
