name: test

on:
  push:
    branches:
      - master
    paths:
      - "client/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test client
        working-directory: ./client
        run: cd client && npm install && npm run test:ci
