name: test

on:
  push:
    branches:
      - master
    paths:
      - "client/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client
      - run: npm install && npm run test:ci
