name: tests-server

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run test
